#!/usr/bin/python3

def raise_exception():
    num_1 = 30
    num_2 = 'H'
    result = num_1 + num_2
    print("{}".format(result))
